openapi: 3.0.4
info:
  title: Unofficial Clicker Heroes API
  description: Unofficial documentation for the backend-API of Clicker Heroes
  version: 0.0.1

tags:
  - name: unauthorized
    description: Endpoints that are available even when not logged in properly
  - name: clan-management
    description: Endpoints for retrieving information for clans
  - name: messages
    description: Endpoints for interaction with clan-chat messages

servers:
  - url: https://guilds.clickerheroes.com
    description: Backend API-Server for Clicker Heroes

paths:
  /clans/findGuild.php:
    $ref: './paths/findGuild.yaml'

  /clans/getGuildInfo.php:
    post:
      summary: Retrieves information for the clan of a logged in user
      tags: [clan-management]
      parameters:
        - $ref: './params/Id.yaml'
        - $ref: './params/Password.yaml'
      responses:
        "200":
          description: The Reponse-Object containing information of the clan
          content:
            text/html:
              schema:
                oneOf:
                  - $ref: './responses/Clan.yaml'
                  - $ref: './responses/Error.yaml'

  /clans/createGuild.php:
    $ref: './paths/createGuild.yaml'

  /clans/disbandGuild.php:
    $ref: './paths/disbandGuild.yaml'

  /clans/kickGuildMember.php:
    $ref: './paths/kickGuildMember.yaml'

  /clans/guildMessageMonitor.php:
    $ref: './paths/guildMessageMonitor.yaml'
